---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
APPLY_FIXES: all
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
ENABLE_LINTERS: 
  - REPOSITORY_SECRETLINT
  - JAVASCRIPT_ES
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM 
  - REPOSITORY_CHECKOV
  - REPOSITORY_DUSTILOCK
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_SYFT
DISABLE:
  - CLOUDFORMATION
  - CSS
  - EDITORCONFIG
  - JAVASCRIPT
  - TEKTON
DISABLE_LINTERS:
  - YAML_YAMLLINT
  - REPOSITORY_TRUFFLEHOG
  - SPELL_CSPELL
  - COPYPASTE_JSCPD
  - CSS_STYLELINT
  - HTML_HTMLHINT
  - JAVASCRIPT_STANDARD
  - REPOSITORY_GITLEAKS
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - HTML_DJLINT
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GRYPE
  - REPOSITORY_SEMGREP
  - SPELL_LYCHEE
  - YAML_YAMLLINT
PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.venv|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)'
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/)'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml)'
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
BASH_FILTER_REGEX_EXCLUDE: "(lib)"
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|docs/licenses)'
SPELL_VALE_FILE_EXTENSIONS:
  - .md
SPELL_FILTER_REGEX_EXCLUDE: (valestyles|\.github|docs/licenses)
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028 --ignore DL3059 --ignore DL4001 --ignore DL4006 --ignore SC2015 --ignore SC2016 --ignore SC2039 --ignore SC2086 --ignore SC1091 --ignore SC3046"
REPOSITORY_TRIVY_ARGUMENTS:
  - "--skip-dirs"
  - ".automation/test"
  - "--skip-dirs"
  - ".venv"
  - "--skip-dirs"
  - "github_conf"
REPOSITORY_TRUFFLEHOG_ARGUMENTS:
  - --exclude-paths=.trufflehogignore
REPOSITORY_KINGFISHER_ARGUMENTS:
  - "--exclude"
  - ".automation/generated"
  - "--exclude"
  - ".automation/test"
  - "--exclude"
  - "docs"
  - "--exclude"
  - "gitleaks-default.toml"
JAVASCRIPT_ES_CONFIG_FILE: ./eslint.config.mjs 
JAVASCRIPT_ES_COMMAND_REMOVE_ARGUMENTS: ["--no-eslintrc"] 
REPORTERS_MARKDOWN_SUMMARY_TYPE: sections
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false